# Site settings
title: 未命名公众号
description: "Purple 小组成立于 2015 年 10 月，……"
baseurl: / # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
permalink: /article-:year-:month-:day-:entitle.htm
